config/routes.rb
Cac2::Application.routes.draw do

  root :to => 'welcome#home'
  get 'about', :to => 'welcome#about'
  get 'contact', :to => 'welcome#contact'
  get 'portfolio', :to => 'welcome#portfolio'
  get 'services', :to => 'welcome#services'
  get 'team', :to => 'welcome#team'
  
  get 'technology', :to => 'welcome#technology', :as => :technology
  get 'privacy-policy', :to => 'welcome#privacy', :as => :privacy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  
  before_filter :set_action_name
  before_filter :set_defaults
  
  private
  
  def set_action_name
    begin
      @action_name = params[:controller].gsub('/', '_') + '_' + params[:action]
    rescue
    end
    
    begin
      @action_classes = params[:controller].gsub('/', '_')
    rescue
    end
    
  end
  
  def set_defaults
    @show_top_ad = true
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  
  def home
    @show_top_ad = false
    
  end
  
  def about
    ;
  end
  
  def contact
    ;
  end
  
  def portfolio
    ;
  end
  
  def services
    ;
  end
  
  def team
    ;
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    { :id => 2 }
  end
  
  def image_contact
    image_tag 'http://s3.amazonaws.com/ish-assets/contact.png', :class => :contact
  end
  
end

app/views/application/_ad_leaderboard.html.erb
<div class="ad-leaderboard">
  <script type="text/javascript"><!--
    google_ad_client = "ca-pub-5283251584689528";
    /* Leaderboard */
    google_ad_slot = "2188944074";
    google_ad_width = 728;
    google_ad_height = 90;
    //-->
  </script>
  <script type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
  </script>
</div>

app/views/application/_analytics.html.haml
- begin

  - if Rails.env.production?

    - unless current_user && current_user[:id] == 1

      :javascript

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-8643197-7']);
        _gaq.push(['_setDomainName', 'infiniteshelter.com']);
        _gaq.push(['_setAllowLinker', true]);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

- rescue

app/views/application/_simplest_nav.html.haml
.simplest-nav
  = link_to ' ', root_path, :class => 'home'
  = link_to ' ', about_path, :class => 'about'
  = link_to ' ', team_path, :class => 'team'
  = link_to ' ', portfolio_path, :class => 'portfolio'
  = link_to ' ', services_path, :class => 'services'
  = link_to ' ', contact_path, :class => 'contact'
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Computational Arts Corp.
    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  %body{ :id => @action_name }
    
    #header
      .container
        %h1 Computatinal Arts Corp.
        = link_to image_tag('logo.png'), root_path
        %ul#main-menu
          %li.about.first
            = link_to t('g.about'), about_path
          %li.team
            = link_to t('g.team'), team_path
          %li.portfolio
            = link_to t('g.portfolio'), portfolio_path
          %li.services
            = link_to t('g.services'), services_path
          %li.contact.last
            = link_to t('g.contact'), contact_path

      - if @show_top_ad
        .clear
        .height-10
        .center
          = render 'ad_leaderboard'
        .height-20

    = yield
    

    .clear
      .height-50
      .center
        = render 'ad_leaderboard'

    #footer
      #stay-connected
        .container
          %p Stay connected
          %ul
            %li.facebook
              %a{:href => '#'} Facebook
            %li.linkedin
              %a{:href => '#'} Linkedin
            %li.subscribe
              %a{:href => '#'} Subscribe
      #posts
        .container
          #popular-posts
            %h2
              %span Most Popular Blog Post:
            %ul.posts
              %li
                %img{:alt => "image", :src => "http://www.placehold.it/45x45"}
                .post-info
                  %span.title Being a Programmer
                  %span.discription Lorem ipsum dolor sit...
                  %em.post-summary
                    %span> August 31st 2012
                    By John Doe
              %li
                %img{:alt => "image", :src => "http://www.placehold.it/45x45"}
                .post-info
                  %span.title Being a Programmer
                  %span.discription Lorem ipsum dolor sit...
                  %em.post-summary
                    %span> August 31st 2012
                    By John Doe
            %ul.pagination
              %li.previous
                %a{:href => '#', :title => "previous"} previous
              %li.next
                %a{:href => '#', :title => "next"} next
          #recent-posts
            %h2
              %span Company News:
            %ul
              %li Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              %li Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              %li Ut enim ad minim veniam, quis nostrud exercitation ullamco.
              %li Laboris nisi ut aliquip ex ea commodo consequat.
              %li Duis aute irure dolor in reprehenderit in voluptate velit.
              %li Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          #connect
            %h2
              %span Receive our eNewsletter:
            %form
              %fieldset
                %input{:placeholder => "Name", :type => "text"}
                %input{:placeholder => "Email", :type => "text"}
                %input{:type => "submit", :value => t('g.subscribe') }
      .details.container
        %p &copy; 2012 Computational Arts Corp.
        = link_to t('g.copyright'), privacy_path

    
    = render 'analytics'

app/views/welcome/about.html.haml
#content
  .container
    %h2= t('g.about')
  .container.overview

    

    %h3 Welcome to Computational Arts Corp.

    = image_tag 'cac.jpg' # %img{:alt => "CAC Team", :src => "http://www.placehold.it/430x210"}

    %p Born in Chicago IL, we are no stranger to midwestern hospitality. Currently operating from San Francisco CA, we are no stranger to modern web development technology. Together, these qualities make us an exceptional company to do business with.
    %p We love helping small and medium-sized businesses achieve their goals. We automate processes. We are good at what we do.
    
  .container.our-process
    %h3 Our Process
    %ul
      %li.first
        Step 1
        %strong Research
        %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      %li
        Step 2
        %strong Design
        %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      %li
        Step 3
        %strong Develop
        %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      %li.last
        Step 4
        %strong Deliver
        %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  .container.choose-us
    %h3 Technology & Software Stack We Use

    %h4 Infrastructure Providers
    %ul
      %li Amazon Web Services (AWS) - preferred provider
      %li Google App Engine
      %li Heroku
      %li Rackspace
      %li Engine Yard

    %h4 OS's
    %ul
      %li Ubuntu is my preferred server and development OS

    %h4 App Servers
    %ul
      %li Nginx
      %li Unicorn - preferred
      %li Passenger
      %li Tomcat
      %li Apache

    %h4 Application Layer Languages
    %ul
      %li PHP
      %li Ruby - preferred
      %li Python
      %li Java SE, EE

    - proc do # hidden
      %h3 Source Control
      %ul
        %li SVN
        %li Git - Github, Bitbucket

      %h3 Bug Tracking & Project Management
      %ul
        %li Jira, Confluence
        %li Trac

    %h4 Frameworks
    %ul
      %li CakePHP
      %li Rails - preferred
      %li Django
      %li Spring

    %h4 Deployment & Monitoring
    %ul
      %li Devops Chef
      %li Capistrano
      %li Nagios

    %h4 Databases
    %ul
      %li Mongodb - preferred
      %li PostgreSQL
      %li MySQL

    %h4 Load Balancers & Reverse Proxies
    %ul
      %li Nginx - preferred
      %li Apache
      %li HAproxy

    .center
      = link_to t('g.contact_us'), contact_path, :class => :button

app/views/welcome/contact.html.haml
#content

  .container

    %h2= t('g.contact_us')

    .map

      -# = image_tag 'map.png'
      = image_tag 'sfbay.jpg'

      %h3 By Mail

      %ul
        %li.address P. O. Box 193023
        %li.address San Francisco, CA 94119
        -# %li.phone +65XX XXXX XXXX

    .contact-methods

      %p Contact us to discuss your project requirements and to get a quote.
      %p 
        We are best reached by email. You may use the form below to send us a message directly to 
        = image_contact

      %h3 By Phone

      %ul
        %li +1 415 948 0368

      -# %h3 By Email

      %div
      
        %form
          %fieldset
            -# %legend Send your email
            %input{:placeholder => "Name", :type => "text"}
            %input{:placeholder => "Email", :type => "text"}
            %input{:placeholder => "Subject", :type => "text"}
            %textarea
              :preserve
            %input{:type => "submit", :value => t('g.send_email')}

      

      

app/views/welcome/home.html.haml
#content
  #slider
    .container
      %h2
        Computational Arts Corp.
        %span is a software engineering & consulting company
  #company_preview
    .container
      %div
        %h2 Computational Arts Corp. is a software engineer & consulting company.
        %em We are a web development shop specializing in full-stack ruby on rails development.
      = link_to t('g.contact_us'), contact_path, :class => :button
  .container
    %ul.workflow
      %li.semantic
        = link_to raw('<strong>Semantic</strong>'), technology_path, :class => :image
        %p
          Our implementation code is semantic. Why does it matter? The technological solution we provide for your needs does not depend on current 
          technology, but stays current with the times. The semantic web releases you from the dependency on any particular technology.
      %li.w3c-valid
        = link_to raw('<strong>W3C Valid</strong>'), technology_path, :class => :image
        %p
          Our code and markup adheres to the latest open web standards. Our process adheres to top modern development practices.
      %li.optimized-speed
        = link_to raw('<strong>Optimized</strong>'), technology_path, :class => :image
        %p We optimize for speed and performance. We maximize your return on investment.
      %li.cross-browser
        = link_to raw('<strong>Cross Platform</strong>'), technology_path, :class => :image
        %p Our code works on all major platforms: Desktop, mobile, iOS, Android, as well as across major browsers.
      %li.responsive
        = link_to raw('<strong>Mobile</strong>'), technology_path, :class => :image
        %p We develop using modern technologies such as responsive design, media queries, HTML5, and mobile jQuery.

app/views/welcome/hosting.html.haml
%h1 Supported Ruby on Rails hosting

%p We provide supposted ruby on rails hosting.

%p What does `supported` mean? If you get stuck at any step in your development process - from coding to testing to deployment - we can help you out on an individual basis.

%p Note: the suppost is charged on specialist' hour basis.

%p= link_to t('g.request_a_quote'), contact_path

app/views/welcome/portfolio.html.haml
#content
  .container
    %h2 Portfolio
    %ul
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 1
        %em Featured Project Description 1
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 2
        %em Featured Project Description 2
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 3
        %em Featured Project Description 3
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 4
        %em Featured Project Description 4
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 5
        %em Featured Project Description 5
      %li
        %img{:alt => "project name", :src => "http://www.placehold.it/280x200"}
        %strong Project Title 6
        %em Featured Project Description 6

app/views/welcome/services.html.haml
#content
  .container
    %h2
      %span.container Services

    .services
      .item
        %h3 Supported Hosting
        %p Confused by the array of hosting options? We provide Ruby hosting at a reasonable rate.  
        %p Our infrastructure provisioning tools are pure Ruby (Devops Chef, Capistrano). 
        %p Internally we use Amazon hosting and can setup Rackspace hosting for your organization upon request.
        
      .item
        %h3 Visual Design
        %p We can act as graphic and web designers providing services such as
        %ul
          %li PSD mockups
          %li PSD to HTML/CSS conversion

      .item
        %h3 Web Development
        %p Software development is our core specialty. We can built custom software to fit your company needs.
        %ul
          %li Small Sites - 1-10 pages, with or without a database, with or without a control panel, static or dynamic.
          %li Large Sites - thousands of pages, control panel, clustered database, exposing and API, integrating with legacy services

      .item
        %h3 Infrastructure Provisioning
        %ul
          %li Migrating from Relational to Non-relational datastores (MySQL to MongoDB migration, including redesign of the model layer)
          %li Installing software - We can help you install most software packages, such as Trac, Mediawiki, and complex Java systems (e.g. Alfresco).

      .item
        %h3 Supported Development
        %div Having trouble deploying your brand-new Rails app? We offer supporting role in that, helping you overcome common and uncommon obstacles.

      .item
        %h3 One-on-One Tutoring for Novice Programmers
        %p 
          If you are a developer and got stuck on a particular project, we can provide tutoring and support. We help you push your project over a bump, 
          at the same time as increasing your knowledge of the stack. You save time and learn - a win-win situation.
        %p We provide support for the following technologies
        %ul
          %li Ruby on Rails
          %li Devops Chef
          %li General Linux Admin
          %li Apache HTTP server
          %li Deploying ready apps
          %li Amazon Web Services (AWS)

      .item
        %h3 Services - Other
        %p Additional Services Include
        %ul
          %li 
            Relational to non-relational Database Migrations
            %ul
              %li MySQL to MongoDB
              %li PostgreSQL to MongoDB

app/views/welcome/team.html.haml
#content
  .container
    %h2 Team
  .container.profile
    %h3 Victor Pudeyev
    %img{:alt => "profile_image", :src => "http://www.placehold.it/370x210"}
    %div
      %h4 CEO, Founder & Programmer
      %ul.stay_connected
        %li.facebook
          %a{:href => ""} Facebook
        %li.linkedin
          %a{:href => ""} Linkin
        %li.subscribe
          %a{:href => ""} Subcribe
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  .container.profile
    %h3 John Doe
    %img{:alt => "profile_image", :src => "http://www.placehold.it/370x210"}
    %div
      %h4 Designer & Slicer
      %ul.stay_connected
        %li.facebook
          %a{:href => ""} Facebook
        %li.linkedin
          %a{:href => ""} Linkin
        %li.subscribe
          %a{:href => ""} Subcribe
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/welcome/technology.html.haml
#welcome_technology
  %h1= t('g.technology')

  %h2 Software Stacks

  %p
    My technology of choice at the moment (Sept 2012) is Ruby on Rails and related. However, I have experience using other software stacks.
    Below is a detailed list categorized by tier.


  %h3 Infrastructure Providers
  %ul
    %li Amazon Web Services (AWS) - preferred provider
    %li Google App Engine
    %li Heroku
    %li Rackspace
    %li Engine Yard

  %h3 OS's
  %ul
    %li Ubuntu is my preferred server and development OS

  %h3 App Servers
  %ul
    %li Nginx
    %li Unicorn - preferred
    %li Passenger
    %li Tomcat
    %li Apache

  %h3 Application Layer Languages
  %ul
    %li PHP
    %li Ruby - preferred
    %li Python
    %li Java SE, EE

  - proc do # hidden
    %h3 Source Control
    %ul
      %li SVN
      %li Git - Github, Bitbucket

    %h3 Bug Tracking & Project Management
    %ul
      %li Jira, Confluence
      %li Trac

  %h3 Frameworks
  %ul
    %li CakePHP
    %li Rails - preferred
    %li Django
    %li Spring

  %h3 Deployment & Monitoring
  %ul
    %li Devops Chef
    %li Capistrano
    %li Nagios

  %h3 Databases
  %ul
    %li Mongodb - preferred
    %li PostgreSQL
    %li MySQL

  %h3 Load Balancers & Reverse Proxies
  %ul
    %li Nginx - preferred
    %li Apache
    %li HAproxy

app/views/welcome/trash/about.html.haml
.about
  = render 'simplest_nav'

app/views/welcome/trash/contact.html.haml
.contact
  = render 'simplest_nav'

app/views/welcome/trash/home.html.haml
.home
  = render 'simplest_nav'

app/views/welcome/trash/portfolio.html.haml
.portfolio
  = render 'simplest_nav'

app/views/welcome/trash/services.html.haml
.services
  = render 'simplest_nav'

app/views/welcome/trash/team.html.haml
.team
  = render 'simplest_nav'